# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a7eb52d3bce7ffaef01c9424d724bf964d50a55d1aa4c72dc7e9554754f319d9ec135732d9794e5f29ea689cc189345b6a9fd6a5e981cad643bc048354e19b7

test:
  secret_key_base: 246730bb3acfaf7b5cd10cbdb15c68b7ddf190e2d19f7975429c935e7ef078658a16434101a2893516a61e499aed25862a666234e8700287736e7809a7530909

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
